"""Added 30 lessons to Lesson model

Revision ID: 0d41fd4471d0
Revises: 0f292c9b60ff
Create Date: 2024-06-17 15:36:12.969377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d41fd4471d0'
down_revision = '0f292c9b60ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson_3', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('lesson_4', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('lesson_5', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('lesson_6', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('lesson_7', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('lesson_8', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('lesson_9', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('lesson_10', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('lesson_11', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('lesson_12', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('lesson_13', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('lesson_14', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('lesson_15', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('lesson_16', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('lesson_17', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('lesson_18', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('lesson_19', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('lesson_20', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('lesson_21', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('lesson_22', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('lesson_23', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('lesson_24', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('lesson_25', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('lesson_26', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('lesson_27', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('lesson_28', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('lesson_29', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_column('lesson_29')
        batch_op.drop_column('lesson_28')
        batch_op.drop_column('lesson_27')
        batch_op.drop_column('lesson_26')
        batch_op.drop_column('lesson_25')
        batch_op.drop_column('lesson_24')
        batch_op.drop_column('lesson_23')
        batch_op.drop_column('lesson_22')
        batch_op.drop_column('lesson_21')
        batch_op.drop_column('lesson_20')
        batch_op.drop_column('lesson_19')
        batch_op.drop_column('lesson_18')
        batch_op.drop_column('lesson_17')
        batch_op.drop_column('lesson_16')
        batch_op.drop_column('lesson_15')
        batch_op.drop_column('lesson_14')
        batch_op.drop_column('lesson_13')
        batch_op.drop_column('lesson_12')
        batch_op.drop_column('lesson_11')
        batch_op.drop_column('lesson_10')
        batch_op.drop_column('lesson_9')
        batch_op.drop_column('lesson_8')
        batch_op.drop_column('lesson_7')
        batch_op.drop_column('lesson_6')
        batch_op.drop_column('lesson_5')
        batch_op.drop_column('lesson_4')
        batch_op.drop_column('lesson_3')

    # ### end Alembic commands ###
