"""Initial migration.

Revision ID: 0f292c9b60ff
Revises: 7ec13056de20
Create Date: 2024-06-17 15:31:18.619349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f292c9b60ff'
down_revision = '7ec13056de20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson_1', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('lesson_2', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('lesson_30', sa.Boolean(), nullable=True))
        batch_op.drop_column('siyer')
        batch_op.drop_column('ilmihal')
        batch_op.drop_column('kurani_kerim')
        batch_op.drop_column('sahsiyet')
        batch_op.drop_column('sure_dua')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sure_dua', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('sahsiyet', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('kurani_kerim', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('ilmihal', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('siyer', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('lesson_30')
        batch_op.drop_column('lesson_2')
        batch_op.drop_column('lesson_1')

    # ### end Alembic commands ###
