"""Initial migration.

Revision ID: 7ec13056de20
Revises: 
Create Date: 2024-06-17 14:54:25.486864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ec13056de20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=50), nullable=False),
    sa.Column('kurani_kerim', sa.Boolean(), nullable=True),
    sa.Column('sure_dua', sa.Boolean(), nullable=True),
    sa.Column('ilmihal', sa.Boolean(), nullable=True),
    sa.Column('sahsiyet', sa.Boolean(), nullable=True),
    sa.Column('siyer', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lesson')
    # ### end Alembic commands ###
